title: At the End of the Day
author: Kasper
description: >
  Welcome to my little space on the internet. 
social_links: 
  twitter: Kasper
  github: KasperLin
theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag
