author: Kasper
name  : At the End of the Day
title : At the End of the Day
url   : https://kasperlin.github.io/
header_pages: 
  - Nav/about.md
  - Nav/notes.md
  - Nav/blogs.md
  - Nav/tags.md
description: >
  Welcome to my little space on the internet. 
show_excerpts: true
social_links: 
  twitter: Kasper
  github: KasperLin
theme: minima
plugins:
  - jekyll-feed
