title: At the End of the Day
author: Kasper
header_pages: 
  - Bar/about.md
  - Bar/notes.md
  - Bar/blogs.md
  - Bar/tags.md
description: >
  Welcome to my little space on the internet. 
show_excerpts: true
social_links: 
  twitter: Kasper
  github: KasperLin
theme: minima
